<img src = "https://drive.google.com/uc?export=view&id=1zD1_7Y4Ejud8OsuQb49rHGfl9qhihAh5" alt = "Encabezado MLDS" width = "100%">  </img>

# **Quiz 2 - Librería numérica de *Python*: *NumPy***
---

Este quiz le servirá para practicar las habilidades adquiridas usando la librería numérica *NumPy*, en el manejo de arreglos y uso de funciones de computación científica.

> **Nota:** Esta tarea va a ser calificada en la plataforma **[UNCode](https://juezun.github.io/)**. Para esto, en cada ejercicio se indicará si es calificable o no, también los lugares donde debe escribir su código sin modificar lo demás con un aproximado de cantidad de líneas a escribir. No se preocupe si su código toma más líneas, esto es simplemente un aproximado destinado a que pueda replantear su estrategia si el código está tomando más de las esperadas. No es un requisito estricto y soluciones más largas también son válidas. Al finalizar, para realizar el envío (*submission*), descargue el notebook como un archivo **`.ipynb`** y haga su entrega a través de la plataforma de aprendizaje.

Ejecute la siguiente celda para importar *NumPy*.

In [1]:
import numpy as np

In [2]:
!python --version
print('NumPy', np.__version__)

Python 3.10.12
NumPy 1.23.5


Este material fue realizado con las siguientes versiones:

*  *Python*: 3.10.6
*  *NumPy*:  1.22.4


> **IMPORTANTE:** Se le recomienda resolver estos ejercicios **sin** usar estructuras de control como **`if`** o **`for`**. Con *NumPy* y *Python* se pueden obtener soluciones muy concisas. Si está acostumbrado a trabajar en lenguajes de programación como *Java* o *C*, se recomienda hacer el esfuerzo de pensar cómo se puede llegar a una solución **sin** usar estructuras de control para sacar un mejor provecho de la conveniente sintaxis de *Python* y sus librerías.

## **1. Normalización**
---

La normalización es una operación muy común en el análisis de datos y el aprendizaje computacional con el cual se pretende obtener una escala y rango común para conjuntos de datos numéricos.

Uno de los métodos de normalización más comunes es la **normalización estándar**, donde se calcula el puntaje estándar (o puntaje $z$) para cada valor y se usa para representar la posición de cada dato con respecto al conjunto. Esta normalización se obtiene al restar la media aritmética a cada dato (centrando los datos) y dividiendo este resultado entre la desviación estándar (reescalando).


> **Nota:** La media aritmética y la desviación estándar son conceptos de estadística descriptiva básica.

La normalización estándar se puede definir mediante la siguiente fórmula:

$$z_i = \frac{x_i - \mu}{\sigma}$$

Donde $\mu$ es la media y $\sigma$ es la desviación estándar de los datos.

En este ejercicio usted deberá implementar la función **`normalizacion`**, que reciba como argumento un arreglo de *NumPy* **`X`** con dimensión **`(n,)`** y retorne un arreglo normalizado con la misma dimensión.




<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Puede calcular la media de un arreglo de *NumPy* con la función **`.mean()`**.
* Puede calcular la desviación estándar de un arreglo de *NumPy* con la función **`.std()`**.
* Recuerde que en *NumPy* los vectores, matrices y valores escalares se pueden operar entre sí directamente usando operadores matemáticos como **`*`** y **`+`**.


In [5]:
# FUNCIÓN CALIFICADA: normalizacion(X)
def normalizacion(X):
  """
  X: un arreglo de NumPy con dimensión (n,)

  Retorna el arreglo X normalizado con dimensión (n,)
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###
  # Reemplace la palabra None por el código correspondiente
  # ~ 4 líneas de código
  # Obtenga la media de los datos.
  media = np.mean(X)
  # Obtenga la desviación estándar de los datos.
  desv = np.std(X)
  # Calcule la normalización.
  X_normalizado = (X - media)/desv
  ### FIN DEL CÓDIGO ###
  return X_normalizado

In [6]:
# CELDA DE PRUEBAS
X0 = np.array([4.8, 4.0, 4.2, 4.0, 5.0])

normalizacion(X0)

array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])

La salida de la celda anterior debería ser:
```
array([ 0.95346259, -0.95346259, -0.47673129, -0.95346259,  1.43019388])
```

In [7]:
# CELDA DE PRUEBAS
X1 = np.arange(5)

normalizacion(X1)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

La salida de la celda anterior debería ser:
```
array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])
```

## **2. Matriz diagonal**
---
En el área de ciencia de datos es muy importante realizar operaciones de álgebra lineal para manipular adecuadamente vectores y matrices de gran tamaño. *NumPy* es una herramienta muy importante para la conceptualización y automatización de este tipo de operaciones.

En este ejercicio deberá implementar la función **`matriz_diagonal`**, que toma una matriz (un arreglo de *NumPy* de $2$ dimensiones) de tamaño $N \times M$ y genera una matriz diagonal con los elementos de su diagonal principal.

> Una matriz diagonal es una matriz cuadrada (misma cantidad de filas que de columnas) que tiene valores nulos ($0$) en todas sus entradas salvo aquellas de la diagonal principal (los elementos cuya fila y columna corresponden).

La matriz a generar debe tener tamaño $L \times L$, donde $L$ es el valor menor entre $N$ y $M$, y deberá ser un arreglo de *NumPy* con dimensiones **`(L, L)`**.


Por ejemplo, para las siguientes matrices el resultado debería ser el siguiente:

* **Para $N$ < $M$**
$$\begin{bmatrix}
1 & 0 & 2 & 9 & 2\\
9 & 2 & 6 & 5 & 7\\
6 & 4 & 3 & 4 & 7
\end{bmatrix} \rightarrow
\begin{bmatrix}
\mathbf{1} & 0 & 0 \\
0 & \mathbf{2 }& 0 \\
0 & 0 & \boldsymbol{\mathbf{}3 }
\end{bmatrix}$$

* **Para $N$ > $M$**
$$\begin{bmatrix}
1 & 0 & 2\\
9 & 2 & 6 \\
6 & 4 & 3 \\
1 & 0 & 5
\end{bmatrix} \rightarrow
\begin{bmatrix}
\mathbf{1} & 0 & 0 \\
0 & \mathbf{2 }& 0 \\
0 & 0 & \boldsymbol{\mathbf{}3 }
\end{bmatrix}$$



<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* El tamaño de la matriz de entrada puede ser obtenido con su atributo **`.shape`**.
* Con la función **`np.eye(n,m)`** puede generar matrices identidad: matrices cuya diagonal tiene el valor de $1$ y el resto de posiciones son $0$.
* Para mantener únicamente los valores originales de la matriz diagonal y dejar los demás valores en $0$, podría realizar operaciones como el producto valor a valor entre la matriz original y una matriz identidad.
* Recuerde que el resultado final de la función debe ser una matriz cuadrada.
* Puede recortar una matriz usando indexado con intervalos.
* A la hora de recortar la matriz debe tener varias cosas en cuenta:
  * ¿Debería cortar el principio o el final?
  * ¿Debería cortar columnas, filas, o ambas? ¿bajo qué condiciones?

In [30]:
# FUNCIÓN CALIFICADA: matriz_diagonal(X)
def matriz_diagonal(X):
  """
  X: un arreglo de NumPy con dimensión (n, m)

  Retorna un arreglo Y con dimensión (n, n) para n < m, ó (m, m) en caso contrario.
  """
  ### ESCRIBA SU CÓDIGO AQUÍ ###
  # Reemplace la palabra None por el código correspondiente
  # ~ 4-5 líneas de código
  # Obtenga el tamaño del arreglo (ancho y alto).
  dim = np.shape(X)
  # Obtenga el tamaño del lado de la matriz a generar.
  L = np.min(dim)

  # Realice operaciones en la matriz para generar Y.
  Y1 = np.eye(L,L)
  X2 = X[0:L, 0:L]
  Y = Y1 * X2

  ### FIN DEL CÓDIGO ###
  return Y


In [31]:
# CELDA DE PRUEBAS
X0 = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])

matriz_diagonal(X0)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

La salida de la celda anterior debería ser:
```
array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])
```

In [32]:
# CELDA DE PRUEBAS
X1 = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]

])

matriz_diagonal(X1)

array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])

La salida de la celda anterior debería ser:
```
array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])
```

**¡Excelente!** Ha terminado el quiz de NumPy. ¡Buen trabajo!

## **Entrega**
Para entregar el notebook por favor haga lo siguiente:
1. Descargue el notebook (`Archivo` -> `Descargar .ipynb`).
2. Ingrese a la plataforma de aprendizaje.
3. Realice el envío del *notebook* que descargó en la tarea (o quiz) correspondiente.
4. Recuerde que si tiene algún error, puede hacer múltiples intentos de envío.

## **Créditos**

* **Profesor:** [Felipe Restrepo Calle](https://dis.unal.edu.co/~ferestrepoca/)
* **Asistente docente:** Alberto Nicolai Romero Martínez
  
**Universidad Nacional de Colombia** - *Facultad de Ingeniería*